# **Airport Filter**
The following code filters the dataset for entries from specific airport for a more narrower analysis.

In [ ]:
import pandas as pd

dataset_path = 'balanced_dataset111.csv'
df = pd.read_csv(dataset_path)

print("Displaying the first 5 rows of the dataset:")
df.head()

Displaying the first 5 rows of the dataset:

,MONTH,DAY_OF_WEEK,DEP_DEL15,DEP_TIME_BLK,DISTANCE_GROUP,SEGMENT_NUMBER,CONCURRENT_FLIGHTS,NUMBER_OF_SEATS,CARRIER_NAME,AIRPORT_FLIGHTS_MONTH,...,PLANE_AGE,DEPARTING_AIRPORT,LATITUDE,LONGITUDE,PREVIOUS_AIRPORT,PRCP,SNOW,SNWD,TMAX,AWND
0,3,7,1,1100-1159,1,3,5,50,Comair Inc.,1555,...,15,McGhee Tyson,35.812,-83.992,Douglas Municipal,0.00,0.0,0.0,59.0,3.80
1,6,7,1,1700-1759,3,4,5,180,Frontier Airlines Inc.,2562,...,5,General Mitchell Field,42.950,-87.897,Orlando International,0.20,0.0,0.0,66.0,3.80
2,10,5,1,2000-2059,3,7,66,66,SkyWest Airlines Inc.,29960,...,14,Chicago O'Hare International,41.978,-87.906,Syracuse Hancock International,0.00,0.0,0.0,59.0,6.93
3,12,2,0,2200-2259,2,5,63,199,Delta Air Lines Inc.,32251,...,19,Atlanta Municipal,33.641,-84.427,Puerto Rico International,0.20,0.0,0.0,68.0,15.66
4,1,2,1,2000-2059,5,4,14,175,Southwest Airlines Co.,5629,...,1,Chicago Midway International,41.785,-87.752,Ronald Reagan Washington National,0.01,0.1,0.0,34.0,7.61

In [ ]:
# extracting and displaying unique airport names
print("List of all unique airport names:")
airport_names = df['DEPARTING_AIRPORT'].unique()
print(airport_names)

print("\nTotal number of unique airports:", len(airport_names))

List of all unique airport names:
['McGhee Tyson' 'General Mitchell Field' "Chicago O'Hare International"
 'Atlanta Municipal' 'Chicago Midway International'
 'Houston Intercontinental' 'Sacramento International'
 'John F. Kennedy International' 'Jacksonville International'
 'Salt Lake City International' 'William P Hobby' 'Logan International'
 'El Paso International' 'Raleigh-Durham International'
 'Seattle International' 'Miami International' 'Kansas City International'
 'Phoenix Sky Harbor International' 'Minneapolis-St Paul International'
 'Newark Liberty International' 'Port Columbus International'
 'San Diego International Lindbergh Fl' 'LaGuardia'
 'Philadelphia International' 'San Jose International'
 'Honolulu International' 'Syracuse Hancock International'
 'Lambert-St. Louis International' 'Washington Dulles International'
 'San Antonio International' 'Dallas Fort Worth Regional'
 'Southwest Florida International' 'Los Angeles International'
 'Douglas Municipal' 'Piedmont Triad International'
 'Metropolitan Oakland International' 'Palm Beach International'
 'Eppley Airfield' 'Cleveland-Hopkins International' 'Tampa International'
 'Albuquerque International Sunport' 'Friendship International'
 'Louis Armstrong New Orleans International' 'McCarran International'
 'Detroit Metro Wayne County' 'Dallas Love Field' 'Kahului Airport'
 'Orlando International' 'Nashville International'
 'San Francisco International' 'Pittsburgh International'
 'Norfolk International' 'Austin - Bergstrom International'
 'Ronald Reagan Washington National' 'Bradley International'
 'Anchorage International' 'Fort Lauderdale-Hollywood International'
 'Stapleton International' 'Greater Buffalo International'
 'Charleston International' 'Memphis International' 'Boise Air Terminal'
 'Greenville-Spartanburg' 'Portland International' 'Tulsa International'
 'Standiford Field' 'Orange County'
 'Cincinnati/Northern Kentucky International' 'Hollywood-Burbank Midpoint'
 'Kent County' 'Spokane International' 'Myrtle Beach International'
 'Rochester Monroe County' 'Reno/Tahoe International' 'Lihue Airport'
 'Palm Springs International' 'Indianapolis Muni/Weir Cook'
 'Northwest Arkansas Regional' 'Ontario International' 'Keahole'
 'Will Rogers World' 'Long Beach Daugherty Field' 'Richmond International'
 'Birmingham Airport' 'Tucson International' 'Adams Field'
 'Albany International' 'Savannah/Hilton Head International' 'Sanford NAS'
 'Truax Field' 'Des Moines Municipal' 'James M Cox/Dayton International'
 'Theodore Francis Green State' 'Portland International Jetport'
 'Pensacola Regional' 'Puerto Rico International']

Total number of unique airports: 96

In [ ]:
# filtering the dataset to only keep rows where DEPARTING_AIRPORT is 'John F. Kennedy International'
filtered_df = df[df['DEPARTING_AIRPORT'] == 'John F. Kennedy International']

# displaying the filtered dataset
print("Filtered dataset with only 'John F. Kennedy International':")
print(filtered_df)

filtered_df.to_csv('filtered_dataset.csv', index=False)

Filtered dataset with only 'John F. Kennedy International':
         MONTH  DAY_OF_WEEK  DEP_DEL15 DEP_TIME_BLK  DISTANCE_GROUP  \
8            5            4          0    1300-1359               3
139         12            1          1    1200-1259              10
168          5            4          0    0700-0759               1
177         10            4          0    0700-0759               5
216         12            6          0    1500-1559               3
...        ...          ...        ...          ...             ...
2454479     11            3          0    1900-1959               1
2454490      8            4          1    1400-1459               4
2454502      7            2          1    1800-1859               4
2454684      9            4          1    1900-1959              10
2454715      8            4          1    1600-1659               3

         SEGMENT_NUMBER  CONCURRENT_FLIGHTS  NUMBER_OF_SEATS  \
8                     3                  20              110
139                   2                  10              159
168                   2                  26              100
177                   2                  22              150
216                   4                  25              100
...                 ...                 ...              ...
2454479               5                  22              132
2454490               1                  25              150
2454502               4                  22              200
2454684               1                  25              160
2454715               2                  25               44

                         CARRIER_NAME  AIRPORT_FLIGHTS_MONTH  ...  PLANE_AGE  \
8                Delta Air Lines Inc.                  10815  ...         17
139                   JetBlue Airways                  10395  ...          2
168                   JetBlue Airways                  10815  ...         10
177                   JetBlue Airways                  10451  ...         15
216                   JetBlue Airways                  10395  ...         13
...                               ...                    ...  ...        ...
2454479          Delta Air Lines Inc.                   9943  ...         17
2454490               JetBlue Airways                  10855  ...         18
2454502               JetBlue Airways                  10704  ...          3
2454684          Delta Air Lines Inc.                  10172  ...         19
2454715  American Eagle Airlines Inc.                  10855  ...         16

                     DEPARTING_AIRPORT  LATITUDE  LONGITUDE  \
8        John F. Kennedy International    40.639    -73.777
139      John F. Kennedy International    40.639    -73.777
168      John F. Kennedy International    40.639    -73.777
177      John F. Kennedy International    40.639    -73.777
216      John F. Kennedy International    40.639    -73.777
...                                ...       ...        ...
2454479  John F. Kennedy International    40.639    -73.777
2454490  John F. Kennedy International    40.639    -73.777
2454502  John F. Kennedy International    40.639    -73.777
2454684  John F. Kennedy International    40.639    -73.777
2454715  John F. Kennedy International    40.639    -73.777

                                PREVIOUS_AIRPORT  PRCP  SNOW SNWD  TMAX   AWND
8                              Douglas Municipal  0.00   0.0  0.0  71.0   7.83
139                    Los Angeles International  0.49   0.0  0.0  43.0  17.90
168                      Rochester Monroe County  0.00   0.0  0.0  71.0   7.83
177                 Salt Lake City International  0.39   0.0  0.0  67.0  16.11
216                      Rochester Monroe County  0.00   0.0  0.0  35.0   4.70
...                                          ...   ...   ...  ...   ...    ...
2454479        Minneapolis-St Paul International  0.00   0.0  0.0  35.0  14.99
2454490                                     NONE  1.18   0.0  0.0  93.0   7.61
2454502  Fort Lauderdale-Hollywood International  0.01   0.0  0.0  88.0   6.71
2454684                                     NONE  0.00   0.0  0.0  82.0   9.40
2454715          Lambert-St. Louis International  0.00   0.0  0.0  85.0   8.50

[47435 rows x 26 columns]